targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          generate_connect_constructor: false
          scoped_dart_components: true
          store_date_time_values_as_text: true
