workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      android_signing:
        - habitly_keystore
      flutter: stable
      java: 21
      vars:
        FLUTTER_BUILD_PLATFORM: android
    
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
        - pattern: develop
          include: true
    
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Generate code
        script: |
          dart run build_runner build --delete-conflicting-outputs
      
      - name: Build Release APK
        script: |
          flutter build apk --release \
            --build-name=1.0.0 \
            --build-number=$((${BUILD_NUMBER:-1}))
      
      - name: Build App Bundle (AAB)
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$((${BUILD_NUMBER:-1}))
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  android-debug:
    name: Android Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    
    environment:
      flutter: stable
      java: 21
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'feature/*'
          include: true
    
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Generate code
        script: |
          dart run build_runner build --delete-conflicting-outputs
      
      - name: Build Debug APK
        script: |
          flutter build apk --debug
    
    artifacts:
      - build/**/outputs/**/*.apk
